Feature: youtube player clone page
StarSheriff2/Youtube-Clone pull request #2
Opened 2020-09-17 22:57 UTC by StarSheriff2

The goal of this project was to clone the Youtube player page using HTML and CSS only

- semantic HTML tags to separate sections
- mostly used flexbox for positioning and centering
- all icons are separate in the image folder
- thumbnail pictures are found in the thumbnail subfolder
- external links and buttons don't work

2020-09-17 23:10 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUIRED♻️

#### Hey team,  your project is looking really good, however, to accomplish as the actual page, you required to do these changes, listed below:
 
_Note_: That changes marked as [OPTIONAL] are not required to approve your project, but I strongly recommend that you guys go for that extra mile, to get more knowledge and have a better project to add at your portfolio.
 
 
## [REQUIRED CHANGES]
- [x] Your page is broken, the video is too big, please fix it.
- [x] Your page has a horizontal bar, please remove it (fixing the size of the elements might work)
![image](https://user-images.githubusercontent.com/56762529/93537162-29dfef00-f921-11ea-84e7-819d78b9a0cf.png)

## [OPTIONAL CHANGES]
**⚠These are mandatory changes, but since It wasn't pointed out earlier, I'll mark them as [OPTIONAL]:**
- [ ] Kindly remember to remove all the unnecessarily repeated CSS code. Keeping your code DRY is an excellent practice that will help you a lot and make your code more professional. (Check this link form better understanding [Good and Bad CSS Practices for Beginners](https://speckyboy.com/good-bad-css-practices/)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)
Take a look at this example:
![image](https://user-images.githubusercontent.com/56762529/90803794-a914df80-e2ef-11ea-9be0-40267c665254.png)
Your HTML will be something like this: 
![image](https://user-images.githubusercontent.com/56762529/90803950-e7120380-e2ef-11ea-8221-5d5d3a13e033.png)
Apply the same logic above in **ALL** those repeated rules listed below:
![image](https://user-images.githubusercontent.com/56762529/93537331-9955de80-f921-11ea-8d2d-c9d761a45f9a.png)

## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-09-18 16:47 UTC, teekaytech reviewed
# Status: Changes Required :recycle: :vertical_traffic_light: 

## Hi team :wave: 
### Nice work on making the changes raised by the previous TSE :muscle: . 
- Your project is looking great. :+1: 
- You have a descriptive readme file. :100: 
- Your codebase is well structured. :+1: 

**However, there are some little changes that need to be made before the project can be approved. Kindly see make the changes listed below and request another review afterward.**

**[REQUIRED]**

- [ ] Right now, you have two icons to the leftmost part of your navbar. Although that is what we have on the original page, but the requirement says you should include one more icon to make it three. You can look at the current youtube page and add any icon that is missing to satisfy this requirement.

![A](https://user-images.githubusercontent.com/26856491/93622826-b3e98f80-f9d5-11ea-9c17-083ce0da0c97.png)

- [ ] Check my in-line comments below :point_down:  and make the changes as required.

**[OPTIONAL]**
_The changes listed here are not required. You can skip them and your project will be approved. However, implementing them makes your project better.
- [ ] You are encouraged to implement the comments section of the page.

![b](https://user-images.githubusercontent.com/26856491/93623464-b4365a80-f9d6-11ea-8ddb-61bdc92928a7.png)

### You're almost there, this is already a great project. Kindly make the finishing touches and request for another review.

* * *

**_You can reach out to me on twitter (@ola_lere), Github (@teekaytech) or slack (@taofeekolalere )_**


Happy Coding :man_technologist:

2020-09-18 16:47 UTC, teekaytech commented on css/styles.css
> +.footer-links a, .footer-help a {
When you are applying a block to multiple selectors (as in line 354), always break individual selector to another line. Something like this: 
```
.footer-links a,
.footer-help a {
--- rules here ---
}
```

2020-09-18 16:47 UTC, teekaytech commented on index.html
> +      </footer>
Nesting this section inside a `<footer>` tag is not necessary. Semantically, the `<footer>` tag has its meaning and it should only be used for the footer section of your page. Kindly replace the footer tag with another tag, probably with a `<div>` or `<section>`

2020-09-18 17:55 UTC, jubaan requested changes
# Status: Changes Required

## :wave: :wave: Hello team! I've seen you applied the suggested changes that's Awesome!

[Mandatory]

- [ ] **search button** separated from the search bar. It's strange as in the **preview image** you have in the **README** it's the code had already solved this issue.

**Actual:**
![image](https://user-images.githubusercontent.com/25774518/93629117-60fbe200-f9ad-11ea-9184-c1b6144ce6df.png)

**README Image**
![image](https://user-images.githubusercontent.com/25774518/93629191-7bce5680-f9ad-11ea-91c6-50e4da5940f6.png)

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!!!



## [NOTES]

It got my attention that you closed the previous pull request. I think this was related to the branch name optional change. If this was the case ```git``` has options to rename local and remote branches. I'll leave you a link that might help in the future. 

- [git branch -m](https://www.w3docs.com/snippets/git/how-to-rename-git-local-and-remote-branches.html)

2020-09-18 18:14 UTC, kevincappuccino requested changes
# [STATUS] CHANGES REQUIRED♻️

#### Hey team,  your project is looking really good, however, to accomplish as the actual page, you required to do these changes, listed below:
 
 
## [REQUIRED CHANGES]
- [ ] Your search button is yet separated from your search input.
- [ ] Your video is still too big and doesn't have left margins.
- Yours
![image](https://user-images.githubusercontent.com/56762529/93630615-a70e7100-f9c0-11ea-803b-b9446f7067e1.png)

- Original
![image](https://user-images.githubusercontent.com/56762529/93630969-3c116a00-f9c1-11ea-83e6-7f40d1cdae42.png)

## [OPTIONAL CHANGES]
- [ ] Improve the layout to make it more similar to the original page.

## Please make the required changes and resubmit for a new code review once you are ready💪

## As always, I wish you all the very best and see you both at the top🚀


👨🏻‍💻 **TSE: Kevin Alves**

  

📫 Have any question? Better call Kevin:

<a  href="mailto:kevinalves.js@gmail.com"> <img  alt="gmail"  src="https://img.shields.io/badge/gmail-%20- green?logo=gmail&style=social"></a> [![Twitter Follow](https://img.shields.io/twitter/follow/kevinnnmn?style=social)](https://twitter.com/intent/follow?screen_name=kevinnnmn) [![](https://img.shields.io/badge/Slack-Kevin%20Alves-green?logo=slack&style=social)](https://microverse-students.slack.com/team/UT86D3AP4)

<sub>*We're here to help you, to ensure that you're using the best practices and getting you ready for the job market. In real-world, you'll have a lot of changes requests for your real clients, it's good to get used to it.</sub>

2020-09-18 19:21 UTC, StarSheriff2 commented
Note: This youtube page was cloned from an old Youtube page from 2014 per project requirements defined in the Microverse pathright site: [](http://archive.vn/Bss88). We tried to make it look as close as possible to that page, and not the current Youtube version.

2020-09-18 19:32 UTC, jubaan approved these changes
# Status: Approved :tada: :tada: :tada:

## Congrats! :smiley: you've worked on all the required changes. You may now merge with master :balloon: :balloon: :clap: :clap: :clap:

2020-09-18 20:37 UTC, merged